package com.librarySystem.corbaDAO;

/**
* corbaDAO/LibraryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaDAO.IDL
* Sunday, 3 March, 2019 1:41:35 AM IST
*/

public final class LibraryHolder implements org.omg.CORBA.portable.Streamable
{
  public com.librarySystem.corbaDAO.Library value = null;

  public LibraryHolder ()
  {
  }

  public LibraryHolder (com.librarySystem.corbaDAO.Library initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.librarySystem.corbaDAO.LibraryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
	  com.librarySystem.corbaDAO.LibraryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.librarySystem.corbaDAO.LibraryHelper.type ();
  }

}
