package com.librarySystem.corbaDAO;


/**
* corbaDAO/Library.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CorbaDAO.IDL
* Sunday, 3 March, 2019 1:41:35 AM IST
*/

public interface Library extends LibraryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Library
