package com.librarySystem.ConcordiaLibraryServer;

/**
* ConcordiaLibraryServer/ConcordiaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConcordiaLibraryServer.idl
* Wednesday, February 27, 2019 1:34:05 o'clock AM EST
*/

public final class ConcordiaHolder implements org.omg.CORBA.portable.Streamable
{
  public Concordia value = null;

  public ConcordiaHolder ()
  {
  }

  public ConcordiaHolder (Concordia initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ConcordiaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ConcordiaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ConcordiaHelper.type ();
  }

}
