package com.librarySystem.ConcordiaLibraryServer;


/**
* ConcordiaLibraryServer/Concordia.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConcordiaLibraryServer.idl
* Saturday, March 2, 2019 2:45:48 o'clock AM EST
*/

public interface Concordia extends ConcordiaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Concordia
