package com.librarySystem.ConcordiaLibraryServer;


/**
* ConcordiaLibraryServer/ConcordiaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConcordiaLibraryServer.idl
* Wednesday, February 27, 2019 1:34:06 o'clock AM EST
*/

public interface ConcordiaOperations 
{
  boolean addItem (String managerID, String itemID, String itemName, int quantity);
  boolean removeItem (String managerID, String itemID, int quantity);
  Item[] listItemAvailability (String managerID);
  String borrowItem (String userID, String itemID, int numberOfDays);
  Item[] findItem (String userID, String itemName);
  boolean returnItem (String userID, String itemID);
  boolean addToQueue (String itemID, String userID);
  boolean exchangeItem (String userID, String oldItem, String newItem);
  boolean checkAvailability (String itemID);
  boolean checkBorrowPossible (String userID, String itemID);
  boolean checkReturnPossible (String userID, String itemID);
  void shutdown ();
} // interface ConcordiaOperations
