package com.librarySystem.ConcordiaLibraryServer;


/**
* ConcordiaLibraryServer/IDLArrayListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConcordiaLibraryServer.idl
* Wednesday, February 27, 2019 1:34:05 o'clock AM EST
*/

public final class IDLArrayListHolder implements org.omg.CORBA.portable.Streamable
{
  public Item value[] = null;

  public IDLArrayListHolder ()
  {
  }

  public IDLArrayListHolder (Item[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IDLArrayListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IDLArrayListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IDLArrayListHelper.type ();
  }

}
