package com.librarySystem.ConcordiaLibraryServer;


/**
* ConcordiaLibraryServer/ItemOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConcordiaLibraryServer.idl
* Wednesday, February 27, 2019 1:34:05 o'clock AM EST
*/

public interface ItemOperations 
{
  String getID();
  String getName();
  String getQuantity();
} // interface ItemOperations
