package com.librarySystem.ConcordiaLibraryServer;

/**
* ConcordiaLibraryServer/ItemHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ConcordiaLibraryServer.idl
* Wednesday, February 27, 2019 1:34:05 o'clock AM EST
*/

public final class ItemHolder implements org.omg.CORBA.portable.Streamable
{
  public Item value = null;

  public ItemHolder ()
  {
  }

  public ItemHolder (Item initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ItemHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ItemHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ItemHelper.type ();
  }

}
