package com.librarySystem.corba;


/**
* corba/Library.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Sunday, 3 March, 2019 1:18:42 AM IST
*/

public interface Library extends LibraryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Library
