package com.librarySystem.McGillLibraryServer;


/**
* McGillLibraryServer/McGill.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from McGillLibraryServer.idl
* Saturday, March 2, 2019 1:42:06 o'clock AM EST
*/

public interface McGill extends McGillOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface McGill
