package com.librarySystem.McGillLibraryServer;


/**
* McGillLibraryServer/McGillOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from McGillLibraryServer.idl
* Saturday, March 2, 2019 1:42:06 o'clock AM EST
*/

public interface McGillOperations 
{
  boolean addItem (String managerID, String itemID, String itemName, int quantity);
  boolean removeItem (String managerID, String itemID, int quantity);
  String listItemAvailability (String managerID);
  String borrowItem (String userID, String itemID, int numberOfDays);
  String findItem (String userID, String itemName);
  boolean returnItem (String userID, String itemID);
  boolean addToQueue (String itemID, String userID);
  boolean exchangeItem (String userID, String oldItem, String newItem);
  boolean checkAvailability (String itemID);
  boolean checkBorrowPossible (String userID, String itemID);
  boolean checkReturnPossible (String userID, String itemID);
  void shutdown ();
} // interface McGillOperations
