package com.librarySystem.McGillLibraryServer;

/**
* McGillLibraryServer/McGillHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from McGillLibraryServer.idl
* Saturday, March 2, 2019 1:42:06 o'clock AM EST
*/

public final class McGillHolder implements org.omg.CORBA.portable.Streamable
{
  public McGill value = null;

  public McGillHolder ()
  {
  }

  public McGillHolder (McGill initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = McGillHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    McGillHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return McGillHelper.type ();
  }

}
