package com.librarySystem.MontrealLibraryServer;


/**
* MontrealLibraryServer/MontrealHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MontrealLibraryServer.idl
* Saturday, March 2, 2019 2:20:01 o'clock AM EST
*/

abstract public class MontrealHelper
{
  private static String  _id = "IDL:MontrealLibraryServer/Montreal:1.0";

  public static void insert (org.omg.CORBA.Any a, Montreal that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Montreal extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (MontrealHelper.id (), "Montreal");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Montreal read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MontrealStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Montreal value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Montreal narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Montreal)
      return (Montreal)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _MontrealStub stub = new _MontrealStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Montreal unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Montreal)
      return (Montreal)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _MontrealStub stub = new _MontrealStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
