package com.librarySystem.MontrealLibraryServer;


/**
* MontrealLibraryServer/Montreal.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MontrealLibraryServer.idl
* Saturday, March 2, 2019 2:20:01 o'clock AM EST
*/

public interface Montreal extends MontrealOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Montreal
