package com.librarySystem.corba;


/**
* corba/Library.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from server.idl
* Monday, March 4, 2019 2:26:32 o'clock PM EST
*/

public interface Library extends LibraryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Library
